manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ftc-zmk
      url-base: https://github.com/ftc/zmk
  projects:
    - name: zmk
      remote: ftc-zmk
      revision: mouse-ftc
      import: app/west.yml
  self:
    path: config
