file_format: "1"
id: corne
name: Corne Dongle
type: shield
#url: https://github.com/benvallack/zmk-config-enki42
url: https://github.com/zmkfirmware/zmk
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - corne_left
  - corne_right
  - corne_dongle
